apiVersion : apps/v1
kind: Deployment
metadata:
  name: nodejstest2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejstest2
  template:
    metadata:
      labels:
        app: nodejstest2 
    spec:
      containers:
        - name: nodejstest2 
          image: kcscr.azurecr.io/nodejstest2
          ports:
          - containerPort: 3000
